In [2]:
# load csv file
import pandas as pd
import numpy as np
df = pd.read_csv('./data/large.csv')
df.head()

        s  a  r      sp
0  291311  3  0  291211
1  291211  9  0  291211
2  291211  1  0  291212
3  291212  7  0  291212
4  291212  6  0  291212

In [3]:
# count the number of unique values in each column
df.nunique()

s     500
a       9
r       7
sp    500
dtype: int64

In [4]:
# create a list that contains unique values in each column
unique_list = []
for i in range(0, len(df.columns)):
    unique_list.append(df.iloc[:, i].unique())

In [5]:
print("action:",unique_list[1])
print("reward:",unique_list[2])

action: [3 9 1 7 6 2 4 8 5]
reward: [  0  10   5  -5  50 100 -10]

In [6]:
set(unique_list[0]) == set(unique_list[3])

True

In [7]:
state = np.array(unique_list[0])
state = np.sort(state)

In [8]:
state.shape

(500,)

In [9]:
state

array([150101, 150102, 150103, 150104, 150110, 150111, 150112, 150113,
       150114, 150120, 150201, 150202, 150203, 150204, 150210, 150211,
       150212, 150213, 150214, 150220, 150301, 150302, 150303, 150304,
       150310, 150311, 150312, 150313, 150314, 150320, 150401, 150402,
       150403, 150404, 150410, 150411, 150412, 150413, 150414, 150420,
       151001, 151002, 151003, 151004, 151010, 151011, 151012, 151013,
       151014, 151020, 151101, 151102, 151103, 151104, 151110, 151111,
       151112, 151113, 151114, 151120, 151201, 151202, 151203, 151204,
       151210, 151211, 151212, 151213, 151214, 151220, 151301, 151302,
       151303, 151304, 151310, 151311, 151312, 151313, 151314, 151320,
       151401, 151402, 151403, 151404, 151410, 151411, 151412, 151413,
       151414, 151420, 152001, 152002, 152003, 152004, 152010, 152011,
       152012, 152013, 152014, 152020, 230101, 230102, 230103, 230104,
       230110, 230111, 230112, 230113, 230114, 230120, 230201, 230202,
       230203, 230204, 230210, 230211, 230212, 230213, 230214, 230220,
       230301, 230302, 230303, 230304, 230310, 230311, 230312, 230313,
       230314, 230320, 230401, 230402, 230403, 230404, 230410, 230411,
       230412, 230413, 230414, 230420, 231001, 231002, 231003, 231004,
       231010, 231011, 231012, 231013, 231014, 231020, 231101, 231102,
       231103, 231104, 231110, 231111, 231112, 231113, 231114, 231120,
       231201, 231202, 231203, 231204, 231210, 231211, 231212, 231213,
       231214, 231220, 231301, 231302, 231303, 231304, 231310, 231311,
       231312, 231313, 231314, 231320, 231401, 231402, 231403, 231404,
       231410, 231411, 231412, 231413, 231414, 231420, 232001, 232002,
       232003, 232004, 232010, 232011, 232012, 232013, 232014, 232020,
       270101, 270102, 270103, 270104, 270110, 270111, 270112, 270113,
       270114, 270120, 270201, 270202, 270203, 270204, 270210, 270211,
       270212, 270213, 270214, 270220, 270301, 270302, 270303, 270304,
       270310, 270311, 270312, 270313, 270314, 270320, 270401, 270402,
       270403, 270404, 270410, 270411, 270412, 270413, 270414, 270420,
       271001, 271002, 271003, 271004, 271010, 271011, 271012, 271013,
       271014, 271020, 271101, 271102, 271103, 271104, 271110, 271111,
       271112, 271113, 271114, 271120, 271201, 271202, 271203, 271204,
       271210, 271211, 271212, 271213, 271214, 271220, 271301, 271302,
       271303, 271304, 271310, 271311, 271312, 271313, 271314, 271320,
       271401, 271402, 271403, 271404, 271410, 271411, 271412, 271413,
       271414, 271420, 272001, 272002, 272003, 272004, 272010, 272011,
       272012, 272013, 272014, 272020, 290101, 290102, 290103, 290104,
       290110, 290111, 290112, 290113, 290114, 290120, 290201, 290202,
       290203, 290204, 290210, 290211, 290212, 290213, 290214, 290220,
       290301, 290302, 290303, 290304, 290310, 290311, 290312, 290313,
       290314, 290320, 290401, 290402, 290403, 290404, 290410, 290411,
       290412, 290413, 290414, 290420, 291001, 291002, 291003, 291004,
       291010, 291011, 291012, 291013, 291014, 291020, 291101, 291102,
       291103, 291104, 291110, 291111, 291112, 291113, 291114, 291120,
       291201, 291202, 291203, 291204, 291210, 291211, 291212, 291213,
       291214, 291220, 291301, 291302, 291303, 291304, 291310, 291311,
       291312, 291313, 291314, 291320, 291401, 291402, 291403, 291404,
       291410, 291411, 291412, 291413, 291414, 291420, 292001, 292002,
       292003, 292004, 292010, 292011, 292012, 292013, 292014, 292020,
       300101, 300102, 300103, 300104, 300110, 300111, 300112, 300113,
       300114, 300120, 300201, 300202, 300203, 300204, 300210, 300211,
       300212, 300213, 300214, 300220, 300301, 300302, 300303, 300304,
       300310, 300311, 300312, 300313, 300314, 300320, 300401, 300402,
       300403, 300404, 300410, 300411, 300412, 300413, 300414, 300420,
       301001, 301002, 301003, 301004, 301010, 301011, 301012, 301013,
       301014, 301020, 301101, 301102, 301103, 301104, 301110, 301111,
       301112, 301113, 301114, 301120, 301201, 301202, 301203, 301204,
       301210, 301211, 301212, 301213, 301214, 301220, 301301, 301302,
       301303, 301304, 301310, 301311, 301312, 301313, 301314, 301320,
       301401, 301402, 301403, 301404, 301410, 301411, 301412, 301413,
       301414, 301420, 302001, 302002, 302003, 302004, 302010, 302011,
       302012, 302013, 302014, 302020], dtype=int64)